id: P224F2066
initial_creation_type: input
source_metadata:
  title: Grammar Series
  language: en
  description: 'Texts related to various aspects of Tibetan grammar and orthography:'
  volume:
    6f2233df61ef41719c5db78a06e68309:
      title: 'The Magical Wish-Fulfilling Tree: The Essence of Thönmi’s Masterpiece
        ''The Thirty Verses'''
      parent: Orthography
created_at: '2022-03-01T03:44:15.437712'
last_modified_at: '2022-03-01T03:44:15.437719'
